name: Run Selenium IDE Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Selenium IDE Runner
        run: npm install -g selenium-side-runner

      # Make sure the .side file path is correct
      - name: Run Selenium IDE Tests
        run: selenium-side-runner test1_orlin_qa_interview.side --output-directory=./results

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: selenium-results
          path: ./results
